create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.organization_invites (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  email text not null,
  invited_by uuid not null references auth.users(id) on delete cascade,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists organization_invites_pending_unique
  on public.organization_invites (organization_id, lower(email))
  where accepted_at is null;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_accounts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create unique index if not exists organization_accounts_name_unique
  on public.organization_accounts (organization_id, lower(btrim(name)));

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title text not null,
  image_path text,
  info text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  quantity integer not null default 0 check (quantity >= 0),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  item_id uuid not null references public.inventory_items(id) on delete cascade,
  delta integer not null,
  note text not null default '',
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  item_id uuid not null references public.inventory_items(id) on delete cascade,
  payment_method text not null check (payment_method in ('Venmo', 'Zelle', 'Cash', 'Other')),
  account text not null default '',
  amount numeric(10, 2) not null check (amount >= 0),
  quantity integer not null check (quantity > 0),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.sale_groups (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  payment_method text not null check (payment_method in ('Venmo', 'Zelle', 'Cash', 'Other')),
  account_id uuid references public.organization_accounts(id) on delete set null,
  account_snapshot text not null default '',
  total_amount numeric(10, 2) not null check (total_amount >= 0),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.account_transfers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  from_account_id uuid references public.organization_accounts(id) on delete set null,
  from_account_snapshot text not null default '',
  to_account_id uuid references public.organization_accounts(id) on delete set null,
  to_account_snapshot text not null default '',
  payment_method text not null default 'Other' check (payment_method in ('Venmo', 'Zelle', 'Cash', 'Other')),
  amount numeric(10, 2) not null check (amount > 0),
  note text not null default '',
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.sales
  add column if not exists sale_group_id uuid references public.sale_groups(id) on delete set null;

alter table public.sales
  add column if not exists account_id uuid references public.organization_accounts(id) on delete set null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_profile_sync()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, lower(coalesce(new.email, '')))
  on conflict (id) do update
  set email = excluded.email,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists inventory_items_set_updated_at on public.inventory_items;
create trigger inventory_items_set_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created_profile_sync on auth.users;
create trigger on_auth_user_created_profile_sync
after insert or update on auth.users
for each row execute function public.handle_profile_sync();

insert into public.profiles (id, email)
select id, lower(coalesce(email, ''))
from auth.users
on conflict (id) do update
set email = excluded.email,
    updated_at = now();

create or replace function public.is_org_member(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members
    where organization_id = org_id
      and user_id = auth.uid()
  );
$$;

create or replace function public.is_org_owner(org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.organization_members
    where organization_id = org_id
      and user_id = auth.uid()
      and role = 'owner'
  );
$$;

create or replace function public.ensure_org_account(org_id uuid, account_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_name text;
  account_id uuid;
begin
  normalized_name := btrim(coalesce(account_name, ''));

  if normalized_name = '' then
    return null;
  end if;

  select id
  into account_id
  from public.organization_accounts
  where organization_id = org_id
    and lower(btrim(name)) = lower(normalized_name)
  limit 1;

  if account_id is not null then
    return account_id;
  end if;

  begin
    insert into public.organization_accounts (organization_id, name, created_by)
    values (org_id, normalized_name, auth.uid())
    returning id into account_id;
  exception
    when unique_violation then
      select id
      into account_id
      from public.organization_accounts
      where organization_id = org_id
        and lower(btrim(name)) = lower(normalized_name)
      limit 1;
  end;

  return account_id;
end;
$$;

create or replace function public.create_organization_workspace(org_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_org_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.organizations (name, created_by)
  values (org_name, auth.uid())
  returning id into new_org_id;

  insert into public.organization_members (organization_id, user_id, role)
  values (new_org_id, auth.uid(), 'owner');

  return new_org_id;
end;
$$;

create or replace function public.claim_pending_org_invites(invited_email text default null)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  pending_email text;
  claimed_count integer := 0;
  invite_row record;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  pending_email := lower(coalesce(invited_email, auth.jwt()->>'email', ''));
  if pending_email = '' then
    return 0;
  end if;

  for invite_row in
    select id, organization_id
    from public.organization_invites
    where accepted_at is null
      and lower(email) = pending_email
  loop
    insert into public.organization_members (organization_id, user_id, role)
    values (invite_row.organization_id, auth.uid(), 'member')
    on conflict (organization_id, user_id) do nothing;

    update public.organization_invites
    set accepted_at = now()
    where id = invite_row.id;

    claimed_count := claimed_count + 1;
  end loop;

  return claimed_count;
end;
$$;

create or replace function public.adjust_inventory_stock(
  org_id uuid,
  inventory_item_id uuid,
  change_delta integer,
  change_note text default ''
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_quantity integer;
  next_quantity integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_org_member(org_id) then
    raise exception 'Not authorized for this organization';
  end if;

  select quantity
  into current_quantity
  from public.inventory_items
  where id = inventory_item_id
    and organization_id = org_id
  for update;

  if current_quantity is null then
    raise exception 'Item not found';
  end if;

  next_quantity := current_quantity + change_delta;
  if next_quantity < 0 then
    raise exception 'Stock cannot go below zero';
  end if;

  update public.inventory_items
  set quantity = next_quantity
  where id = inventory_item_id
    and organization_id = org_id;

  insert into public.stock_movements (
    organization_id,
    item_id,
    delta,
    note,
    created_by
  )
  values (
    org_id,
    inventory_item_id,
    change_delta,
    coalesce(change_note, ''),
    auth.uid()
  );

  return next_quantity;
end;
$$;

create or replace function public.record_inventory_sale(
  org_id uuid,
  inventory_item_id uuid,
  sale_payment_method text,
  sale_account text default '',
  sale_amount_override numeric default null,
  sale_quantity integer default 1
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  current_price numeric(10, 2);
  current_quantity integer;
  next_quantity integer;
  sale_amount numeric(10, 2);
  sale_note text;
  resolved_account_id uuid;
  new_group_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_org_member(org_id) then
    raise exception 'Not authorized for this organization';
  end if;

  if sale_quantity < 1 then
    raise exception 'Sale quantity must be at least 1';
  end if;

  if sale_payment_method not in ('Venmo', 'Zelle', 'Cash', 'Other') then
    raise exception 'Invalid payment method';
  end if;

  select price, quantity
  into current_price, current_quantity
  from public.inventory_items
  where id = inventory_item_id
    and organization_id = org_id
  for update;

  if current_quantity is null then
    raise exception 'Item not found';
  end if;

  if current_quantity < sale_quantity then
    raise exception 'Not enough stock to record this sale';
  end if;

  sale_amount := coalesce(sale_amount_override, current_price * sale_quantity);
  if sale_amount < 0 then
    raise exception 'Sale amount must be positive';
  end if;

  resolved_account_id := public.ensure_org_account(org_id, sale_account);

  sale_note := 'Sale: ' || sale_payment_method;
  if coalesce(trim(sale_account), '') <> '' then
    sale_note := sale_note || ', Account: ' || sale_account;
  end if;
  if sale_amount_override is not null then
    sale_note := sale_note || ', OR Price: $' || trim(to_char(sale_amount_override, 'FM999999990.00'));
  end if;

  next_quantity := current_quantity - sale_quantity;

  insert into public.sale_groups (
    organization_id,
    payment_method,
    account_id,
    account_snapshot,
    total_amount,
    created_by
  )
  values (
    org_id,
    sale_payment_method,
    resolved_account_id,
    coalesce(btrim(sale_account), ''),
    sale_amount,
    auth.uid()
  )
  returning id into new_group_id;

  insert into public.sales (
    organization_id,
    sale_group_id,
    item_id,
    payment_method,
    account_id,
    account,
    amount,
    quantity,
    created_by
  )
  values (
    org_id,
    new_group_id,
    inventory_item_id,
    sale_payment_method,
    resolved_account_id,
    coalesce(sale_account, ''),
    sale_amount,
    sale_quantity,
    auth.uid()
  );

  update public.inventory_items
  set quantity = next_quantity
  where id = inventory_item_id
    and organization_id = org_id;

  insert into public.stock_movements (
    organization_id,
    item_id,
    delta,
    note,
    created_by
  )
  values (
    org_id,
    inventory_item_id,
    sale_quantity * -1,
    sale_note,
    auth.uid()
  );

  return next_quantity;
end;
$$;

create or replace function public.record_multi_item_sale(
  org_id uuid,
  sale_payment_method text,
  sale_account text default '',
  sale_lines jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  line_item record;
  current_price numeric(10, 2);
  current_quantity integer;
  sale_total numeric(10, 2) := 0;
  resolved_account_id uuid;
  new_group_id uuid;
  requested_quantity integer;
  sale_note text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_org_member(org_id) then
    raise exception 'Not authorized for this organization';
  end if;

  if sale_payment_method not in ('Venmo', 'Zelle', 'Cash', 'Other') then
    raise exception 'Invalid payment method';
  end if;

  if jsonb_typeof(sale_lines) <> 'array' or jsonb_array_length(sale_lines) = 0 then
    raise exception 'At least one item is required';
  end if;

  resolved_account_id := public.ensure_org_account(org_id, sale_account);

  for line_item in
    select
      (value->>'itemId')::uuid as item_id,
      greatest(1, coalesce((value->>'quantity')::integer, 0)) as quantity
    from jsonb_array_elements(sale_lines)
  loop
    requested_quantity := line_item.quantity;

    select price, quantity
    into current_price, current_quantity
    from public.inventory_items
    where id = line_item.item_id
      and organization_id = org_id
    for update;

    if current_quantity is null then
      raise exception 'Item not found in multi-sell';
    end if;

    if current_quantity < requested_quantity then
      raise exception 'Not enough stock for one of the selected items';
    end if;

    sale_total := sale_total + (current_price * requested_quantity);
  end loop;

  insert into public.sale_groups (
    organization_id,
    payment_method,
    account_id,
    account_snapshot,
    total_amount,
    created_by
  )
  values (
    org_id,
    sale_payment_method,
    resolved_account_id,
    coalesce(btrim(sale_account), ''),
    sale_total,
    auth.uid()
  )
  returning id into new_group_id;

  for line_item in
    select
      (value->>'itemId')::uuid as item_id,
      greatest(1, coalesce((value->>'quantity')::integer, 0)) as quantity
    from jsonb_array_elements(sale_lines)
  loop
    requested_quantity := line_item.quantity;

    select price, quantity
    into current_price, current_quantity
    from public.inventory_items
    where id = line_item.item_id
      and organization_id = org_id
    for update;

    update public.inventory_items
    set quantity = current_quantity - requested_quantity
    where id = line_item.item_id
      and organization_id = org_id;

    insert into public.sales (
      organization_id,
      sale_group_id,
      item_id,
      payment_method,
      account_id,
      account,
      amount,
      quantity,
      created_by
    )
    values (
      org_id,
      new_group_id,
      line_item.item_id,
      sale_payment_method,
      resolved_account_id,
      coalesce(sale_account, ''),
      current_price * requested_quantity,
      requested_quantity,
      auth.uid()
    );

    sale_note := 'Sale: ' || sale_payment_method;
    if coalesce(trim(sale_account), '') <> '' then
      sale_note := sale_note || ', Account: ' || sale_account;
    end if;

    insert into public.stock_movements (
      organization_id,
      item_id,
      delta,
      note,
      created_by
    )
    values (
      org_id,
      line_item.item_id,
      requested_quantity * -1,
      sale_note,
      auth.uid()
    );
  end loop;

  return new_group_id;
end;
$$;

create or replace function public.record_account_transfer(
  org_id uuid,
  from_account_name text,
  to_account_name text,
  transfer_payment_method text,
  transfer_amount numeric,
  transfer_note text default ''
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  from_account_id uuid;
  to_account_id uuid;
  transfer_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_org_member(org_id) then
    raise exception 'Not authorized for this organization';
  end if;

  if transfer_amount <= 0 then
    raise exception 'Transfer amount must be positive';
  end if;

  if transfer_payment_method not in ('Venmo', 'Zelle', 'Cash', 'Other') then
    raise exception 'Invalid payment method';
  end if;

  if btrim(coalesce(from_account_name, '')) = '' or btrim(coalesce(to_account_name, '')) = '' then
    raise exception 'Both accounts are required';
  end if;

  from_account_id := public.ensure_org_account(org_id, from_account_name);
  to_account_id := public.ensure_org_account(org_id, to_account_name);

  insert into public.account_transfers (
    organization_id,
    from_account_id,
    from_account_snapshot,
    to_account_id,
    to_account_snapshot,
    payment_method,
    amount,
    note,
    created_by
  )
  values (
    org_id,
    from_account_id,
    btrim(from_account_name),
    to_account_id,
    btrim(to_account_name),
    transfer_payment_method,
    transfer_amount,
    coalesce(transfer_note, ''),
    auth.uid()
  )
  returning id into transfer_id;

  return transfer_id;
end;
$$;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.organization_invites enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_accounts enable row level security;
alter table public.inventory_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.sales enable row level security;
alter table public.sale_groups enable row level security;
alter table public.account_transfers enable row level security;

drop policy if exists "org members can view organizations" on public.organizations;
create policy "org members can view organizations"
  on public.organizations
  for select
  using (public.is_org_member(id));

drop policy if exists "authenticated users can create organizations" on public.organizations;
create policy "authenticated users can create organizations"
  on public.organizations
  for insert
  with check (auth.uid() = created_by);

drop policy if exists "org members can view members" on public.organization_members;
create policy "org members can view members"
  on public.organization_members
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "owners can add members" on public.organization_members;
create policy "owners can add members"
  on public.organization_members
  for insert
  with check (public.is_org_owner(organization_id));

drop policy if exists "org members can view invites" on public.organization_invites;
create policy "org members can view invites"
  on public.organization_invites
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can view profiles" on public.profiles;
create policy "org members can view profiles"
  on public.profiles
  for select
  using (
    exists (
      select 1
      from public.organization_members current_member
      join public.organization_members target_member
        on target_member.organization_id = current_member.organization_id
      where current_member.user_id = auth.uid()
        and target_member.user_id = profiles.id
    )
  );

drop policy if exists "owners can create invites" on public.organization_invites;
create policy "owners can create invites"
  on public.organization_invites
  for insert
  with check (public.is_org_owner(organization_id));

drop policy if exists "owners can update invites" on public.organization_invites;
create policy "owners can update invites"
  on public.organization_invites
  for update
  using (
    public.is_org_owner(organization_id)
    or lower(email) = lower(coalesce(auth.jwt()->>'email', ''))
  )
  with check (
    public.is_org_owner(organization_id)
    or lower(email) = lower(coalesce(auth.jwt()->>'email', ''))
  );

drop policy if exists "org members can view inventory" on public.inventory_items;
create policy "org members can view inventory"
  on public.inventory_items
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can add inventory" on public.inventory_items;
create policy "org members can add inventory"
  on public.inventory_items
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

drop policy if exists "org members can update inventory" on public.inventory_items;
create policy "org members can update inventory"
  on public.inventory_items
  for update
  using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

drop policy if exists "org members can delete inventory" on public.inventory_items;
create policy "org members can delete inventory"
  on public.inventory_items
  for delete
  using (public.is_org_member(organization_id));

drop policy if exists "org members can view stock movements" on public.stock_movements;
create policy "org members can view stock movements"
  on public.stock_movements
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can create stock movements" on public.stock_movements;
create policy "org members can create stock movements"
  on public.stock_movements
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

drop policy if exists "org members can view sales" on public.sales;
create policy "org members can view sales"
  on public.sales
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can create sales" on public.sales;
create policy "org members can create sales"
  on public.sales
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

drop policy if exists "org members can view accounts" on public.organization_accounts;
create policy "org members can view accounts"
  on public.organization_accounts
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can create accounts" on public.organization_accounts;
create policy "org members can create accounts"
  on public.organization_accounts
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

drop policy if exists "org members can view sale groups" on public.sale_groups;
create policy "org members can view sale groups"
  on public.sale_groups
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can create sale groups" on public.sale_groups;
create policy "org members can create sale groups"
  on public.sale_groups
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

drop policy if exists "org members can view account transfers" on public.account_transfers;
create policy "org members can view account transfers"
  on public.account_transfers
  for select
  using (public.is_org_member(organization_id));

drop policy if exists "org members can create account transfers" on public.account_transfers;
create policy "org members can create account transfers"
  on public.account_transfers
  for insert
  with check (public.is_org_member(organization_id) and auth.uid() = created_by);

insert into storage.buckets (id, name, public)
values ('item-images', 'item-images', true)
on conflict (id) do nothing;

drop policy if exists "authenticated users can read item images" on storage.objects;
create policy "authenticated users can read item images"
  on storage.objects
  for select
  using (bucket_id = 'item-images' and auth.role() = 'authenticated');

drop policy if exists "authenticated users can upload item images" on storage.objects;
create policy "authenticated users can upload item images"
  on storage.objects
  for insert
  with check (bucket_id = 'item-images' and auth.role() = 'authenticated');

drop policy if exists "authenticated users can update item images" on storage.objects;
create policy "authenticated users can update item images"
  on storage.objects
  for update
  using (bucket_id = 'item-images' and auth.role() = 'authenticated')
  with check (bucket_id = 'item-images' and auth.role() = 'authenticated');

drop policy if exists "authenticated users can delete item images" on storage.objects;
create policy "authenticated users can delete item images"
  on storage.objects
  for delete
  using (bucket_id = 'item-images' and auth.role() = 'authenticated');
